[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.19"
evm_version = 'cancun'
optimizer = true
optimizer_runs = 200

[lint]
exclude_lints = [
    "unaliased-plain-import",
    "mixed-case-function",
    "mixed-case-variable",
    "screaming-snake-case-const",
    "named-struct-fields",
    "unwrapped-modifier-logic",
]
